log_settings:
  log_level: log
  log_file_bool: true
  log_file_name: logs
  log_file_extension: .log

log_colors:
  info_color: "blue"
  warning_color: "yellow"
  error_color: "red"
  danger_color: "magenta"
  default_color: "cyan"
